#!/usr/bin/env python

#Starting coordinates inputted during the restart service call by the restart function in the follow node to send 
# the turtle to an initial position and calculate the total travel distance
float64 start_x
float64 start_y
---
#Value returned by the restart function in the follow node after the total travel distance is calculated
float64 total_distance